---
title: "Conclusion"
#bibliography: references.bib
author: "Bram Koeweiden"
bibliography: references.bib
---

# Conclusion

The goal of this study was to study how individual choices of academics to collaborate within or between universities, create network structures which could explain the gender inequality in science. To this end, the changes in the publication networks of Dutch sociologists and political scientists as a result of individual behaviour have been studied. Theoretically this approach is beneficial as it can show how sensible behaviour of individuals could lead to undesirable results on a societal level.

To understand what the publication networks look like across the three waves, the distribution of inter and intra-university collaborations was measured descriptively in all three waves and the gender split in this disribution was examined. In line with the first hypothesis, there are much more collaborations within universities than between universities. However, contrary to the second hypotheses, the data did not show a clear pattern of gender differences in the degree to which scholars collaborate within or between universities. To formally test if collaboration preferences shape network evolution, hypothesis 3 and 4 were answered using stochastic actor oriented modeling with RSiena [@RSiena]. The results show that the preference for within university collaboration over collaboration between universities is a relevant factor in how publication networks evolve which is in support of hypothesis 3. However, the data does not support hypothesis 4 which stated that women would have a stronger intra-university preference as pervasive gender norms lead them to have less free time than men [@jaspers2022]. In the results gender differences in intra-university preference do not seem to be relevant in predicting change in publication networks.

Theoretically the lack of gender difference in collaboration preference might be attributable to wrong assumptions about the reality of scientific collaboration. In the current digital age, a lot of work can be done remotely thus making traveltime a much less relevant factor than it might have been in the past. Furthermore, the theory is based on the first author having a most agency in collaboration choices. In reality, junior researchers like PhD students might be more dependent in who their supervisor wants to collaborate with meaning that they are in reality not always the ones choosing their coauthors based on preferences and restrictions. This could have been particularly relevant as PhD students were the biggest function level category in our data were likely an important driver of network change. Aside from scientific collaboration structure, the assumptions about restrictions might also not translate well to the researched context. @jaspers2022 describe gender differences in free time due to household chores, but these become particularly straining after the birth of children. As the average age of a first child in the Netherlands is now over 30 [@statline], these restrictions might only become relevant for most scholars after their PhD and are therefore not represented well by the current data.

Methodologically, the way collaboration networks were created might have also diminished the reliability of the results. The current approach measured the publications in each wave, independent of the publications before that. As a result, the waves had very little overlap which is a risk for the reliability of stochastic actor oriented models. For future studies it might be valuable to keep the collaborations in previous waves in the data for all subsequent waves to more reliably estimate the network effects of individual behaviour[^1]. Still, the results of the dynamic network analysis make sense in light of the descriptive results. Thus while the estimation might not have been reliable, the results likely reflect reality decently well.

[^1]: I know the data allow me to do this myself. However, as the goal is learning and not writing a publishable paper, I decided the time trade off would not be worth the possible gain in knowledge of social network analysis.

In this study we attempted to find a possible network explanation in publication network structure for the leaky pipeline of female academic career progression [@mulders2024; @teelken2013]. This approach was based on an assumption that the collaboration actions of scholars determine their network which could predict their succes. While this might be true, for stepping outside ones university bubble these choices do not seem to depend on gender. In order to finally patch up the leaky pipeline, a focus on the actions of those affording women opportunities rather than the women themselves might be merited.
