---
title: "Week 1"
#bibliography: references.bib
author: "Bram Koeweiden"
bibliography: references.bib
---

```{r, globalsettings, echo=FALSE, warning=FALSE, results='hide'}
library(knitr)

knitr::opts_chunk$set(echo = TRUE)
opts_chunk$set(tidy.opts=list(width.cutoff=100),tidy=TRUE, warning = FALSE, message = FALSE,comment = "#>", cache=TRUE, class.source=c("test"), class.output=c("test2"))
options(width = 100)
#rgl::setupKnitr()



colorize <- function(x, color) {sprintf("<span style='color: %s;'>%s</span>", color, x) }

```

```{r klippy, echo=FALSE, eval=FALSE, include=TRUE}
klippy::klippy(position = c('top', 'right'))
klippy::klippy(color = 'darkred')
klippy::klippy(tooltip_message = 'Click to copy', tooltip_success = 'Done')
```

Last compiled on `r format(Sys.time(), '%B, %Y')`

<br>

------------------------------------------------------------------------

week 1: research questions

@granovetter1973 posited long ago that social network structures are crucial in conecting micro and macro level phenomena. His theory is centered around the idea that ties between dense social networks, weak ties, are crucial in transmitting information as 'strong ties' in dense networks often transmit a lot of redundant information. This insight is shown to be particularly relevant for scientific collaboration networks as scientists with more weak ties are shown to have markedly higher H-indexes than scientists with fewer weak ties [@fronczak2022].

The trouble with the strength of weak ties finding in scientific collaboration networks is that it is hard to untangle whether this is caused by the quality of the research or the popularity of the researchers. To shed some light on this issue the present study will take the type of weak tie into account. If the increased H-index due to weak ties is purely caused by popularity, the type of weak ties should not matter. However, the mechanism leading to increased quality is based on weak ties providing novel insights leading to creative research. As scientific disciplines are defined by their disciplinary norms and boundaries [@hui2016], creating interdisciplinary weak ties might be more beneficial than regular weak ties. Thus comparing the strength of weak ties within and between disciplines might aid understanding of the true societal benefit of weak ties in scientific collaboration.

Research questions:

1: To what extent do researchers with more weak ties have higher H-indexes than scientists with fewer weak ties in the fields of sociology and political science in the Netherlands?

2: To what degree does the proportion of interdisciplinary weak ties increase or decrease the relationship between amount of weak ties and H-index?

------------------------------------------------------------------------

References

Ronald Burt
